export const FETCH_MOVIES = 'FETCH_MOVIES';
export const ERROR_MOVIES = 'ERROR_MOVIES';
export const LOADING_MOVIES = 'LOADING_MOVIES';

export const FETCH_LOAD_MORE_MOVIES = 'FETCH_LOAD_MORE_MOVIES';

export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
