export const FETCH_MOVIES = 'FETCH_MOVIES';
export const ERROR_MOVIES_TRUE = 'ERROR_MOVIES_TRUE';
export const ERROR_MOVIES_FALSE = 'ERROR_MOVIES_FALSE';
export const LOADING_MOVIES_TRUE = 'LOADING_MOVIES_TRUE';
export const LOADING_MOVIES_FALSE = 'LOADING_MOVIES_FALSE';

export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
